/**
 *Thisfileaddsa'guardedCatch'functiontothePromiseAPI.Thisfunction
 *hastobeusedwhenwedon'twanttoswallowrealerrors(crashes),like
 *'catch'does(i.e.basicallyallthetimeinFlectra).Weonlyexecutethe
 *'onRejected'handleriftherejection'sreasonisnotanError,andwealways
 *returnarejectedPromisetolettherejectionbubbleup(andtriggerthe
 *'unhandledrejection'event).
 */

(function(){
    var_catch=Promise.prototype.catch;
    Promise.prototype.guardedCatch=function(onRejected){
        return_catch.call(this,function(reason){
            if(!reason||!(reasoninstanceofError)){
                if(onRejected){
                    onRejected.call(this,reason);
                }
            }
            returnPromise.reject(reason);
        });
    };
})();
